export const ALL_ACCESSORIES_REQUEST = "ALL_ACCESSORIES_REQUEST";
export const ALL_ACCESSORIES_SUCCESS = "ALL_ACCESSORIES_SUCCESS";
export const ALL_ACCESSORIES_FAIL = "ALL_ACCESSORIES_FAIL";

export const ADMIN_ACCESSORIES_REQUEST = "ADMIN_ACCESSORIES_REQUEST";
export const ADMIN_ACCESSORIES_SUCCESS = "ADMIN_ACCESSORIES_SUCCESS";
export const ADMIN_ACCESSORIES_FAIL = "ADMIN_ACCESSORIES_FAIL";

export const ACCESSORIES_DETAILS_REQUEST = "ACCESSORIES_DETAILS_REQUEST";
export const ACCESSORIES_DETAILS_SUCCESS = "ACCESSORIES_DETAILS_SUCCESS";
export const ACCESSORIES_DETAILS_FAIL = "ACCESSORIES_DETAILS_FAIL";

export const NEW_ACCESSORIES_REQUEST = "NEW_ACCESSORIES_REQUEST";
export const NEW_ACCESSORIES_SUCCESS = "NEW_ACCESSORIES_SUCCESS";
export const NEW_ACCESSORIES_RESET = "NEW_ACCESSORIES_RESET";
export const NEW_ACCESSORIES_FAIL = "NEW_ACCESSORIES_FAIL";

export const DELETE_ACCESSORIES_REQUEST = "DELETE_ACCESSORIES_REQUEST";
export const DELETE_ACCESSORIES_SUCCESS = "DELETE_ACCESSORIES_SUCCESS";
export const DELETE_ACCESSORIES_RESET = "DELETE_ACCESSORIES_RESET";
export const DELETE_ACCESSORIES_FAIL = "DELETE_ACCESSORIES_FAIL";

export const UPDATE_ACCESSORIES_REQUEST = "UPDATE_ACCESSORIES_REQUEST";
export const UPDATE_ACCESSORIES_SUCCESS = "UPDATE_ACCESSORIES_SUCCESS";
export const UPDATE_ACCESSORIES_RESET = "UPDATE_ACCESSORIES_RESET";
export const UPDATE_ACCESSORIES_FAIL = "UPDATE_ACCESSORIES_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
