export const ADMIN_UNIT_REQUEST = "ADMIN_UNIT_REQUEST";
export const ADMIN_UNIT_SUCCESS = "ADMIN_UNIT_SUCCESS";
export const ADMIN_UNIT_FAIL = "ADMIN_UNIT_FAIL";

// export const UNIT_DETAILS_REQUEST = "UNIT_DETAILS_REQUEST";
// export const UNIT_DETAILS_SUCCESS = "UNIT_DETAILS_SUCCESS";
// export const UNIT_DETAILS_FAIL = "UNIT_DETAILS_FAIL";

export const NEW_UNIT_REQUEST = "NEW_UNIT_REQUEST";
export const NEW_UNIT_SUCCESS = "NEW_UNIT_SUCCESS";
export const NEW_UNIT_RESET = "NEW_UNIT_RESET";
export const NEW_UNIT_FAIL = "NEW_UNIT_FAIL";

export const DELETE_UNIT_REQUEST = "DELETE_UNIT_REQUEST";
export const DELETE_UNIT_SUCCESS = "DELETE_UNIT_SUCCESS";
export const DELETE_UNIT_RESET = "DELETE_UNIT_RESET";
export const DELETE_UNIT_FAIL = "DELETE_UNIT_FAIL";

export const UPDATE_UNIT_REQUEST = "UPDATE_UNIT_REQUEST";
export const UPDATE_UNIT_SUCCESS = "UPDATE_UNIT_SUCCESS";
export const UPDATE_UNIT_RESET = "UPDATE_UNIT_RESET";
export const UPDATE_UNIT_FAIL = "UPDATE_UNIT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
